apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb-logs
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: logs
    secureJsonData:
      token: EuHWeJqtAv3iw42scK6rLJLJX3_NA5EuYl_Jek3kdqey_BGYC1GbryzIFJvUzPTwb1lP-HmYVp-uUUjZdMlrmQ==
