apiVersion: 1
contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: fenh5ih73isjkb
        type: telegram
        settings:
          bottoken: 8172712346:AAGogUFjKCJagmjsjWgxm5rLYaKE_lkAEFc
          chatid: "-4904439223"
          disable_notification: false
          disable_web_page_preview: false
          protect_content: false
        disableResolveMessage: false
